import type {
  V2CarouselBodyTemplate,
  V2Palette,
  V2TitleSlideTemplate,
} from './template-types-v2';

export const NMF_BRAND_TOKENS = {
  color: {
    inkPrimary: '#0F1B33',
    accentTeal: '#3EE6C3',
    accentGold: '#F5C453',
    warmGold: '#D4A843',
    ivory: '#F5E6B8',
    paper: '#FAFAF6',
    rose: '#FF69B4',
    rust: '#C8511C',
    turquoise: '#2DAFAA',
  },
  font: {
    display: 'Playfair Display',
    body: 'Source Serif 4',
    sans: 'DM Sans',
    mono: 'JetBrains Mono',
    script: 'Dancing Script',
  },
} as const;

export const V2_PALETTES = {
  mmmcClassic: {
    bg: '#ffffff',
    accent: NMF_BRAND_TOKENS.color.inkPrimary,
    accent2: NMF_BRAND_TOKENS.color.warmGold,
    text: NMF_BRAND_TOKENS.color.inkPrimary,
    textMuted: '#1f2c4a',
  },
  velvetRoom: {
    bg: '#1a0f17',
    accent: '#FFD7A8',
    accent2: NMF_BRAND_TOKENS.color.rose,
    text: '#FFD7A8',
    textMuted: '#c9a387',
  },
  neonCity: {
    bg: '#0a0420',
    accent: NMF_BRAND_TOKENS.color.accentTeal,
    accent2: '#FF2E97',
    text: NMF_BRAND_TOKENS.color.accentTeal,
    textMuted: '#9ad9c8',
  },
  honkyTonk: {
    bg: '#f4ead0',
    accent: '#1a1610',
    accent2: NMF_BRAND_TOKENS.color.rust,
    text: '#1a1610',
    textMuted: '#5a4a30',
  },
  stadiumLights: {
    bg: '#0a1428',
    accent: '#FFD24A',
    accent2: '#FF5C8A',
    text: '#FFEFC4',
    textMuted: '#a9b9d5',
  },
  pearlSnap: {
    bg: NMF_BRAND_TOKENS.color.paper,
    accent: '#0a0a0a',
    accent2: NMF_BRAND_TOKENS.color.turquoise,
    text: '#0a0a0a',
    textMuted: '#3a3a3a',
  },
} satisfies Record<string, V2Palette>;

const serifFonts = {
  display: NMF_BRAND_TOKENS.font.display,
  body: NMF_BRAND_TOKENS.font.body,
  mono: NMF_BRAND_TOKENS.font.mono,
};

const sansFonts = {
  display: NMF_BRAND_TOKENS.font.sans,
  body: NMF_BRAND_TOKENS.font.sans,
  mono: NMF_BRAND_TOKENS.font.mono,
};

export const V2_BODY_TEMPLATE_PRESETS: V2CarouselBodyTemplate[] = [
  {
    id: 'v2_mmmc_classic',
    name: 'MMMC Classic v2',
    description: 'Clean white background with deep navy and gold accents',
    engine: 'v2',
    kind: 'body',
    palette: V2_PALETTES.mmmcClassic,
    fonts: serifFonts,
    cellPadding: 14,
    cellRadius: 8,
    cellShadow: '0 8px 24px rgba(15,27,51,.18)',
    cellRotate: [-1.5, 1, -0.5, 1.8, -1.2, 0.8, -1.6, 1.4, -0.7],
    decoration: 'gold-frame',
    showGrain: true,
    grainOpacity: 0.04,
  },
  {
    id: 'v2_velvet_room',
    name: 'Velvet Room',
    description: 'Plush black-and-rose intimate club energy',
    engine: 'v2',
    kind: 'body',
    palette: V2_PALETTES.velvetRoom,
    fonts: serifFonts,
    cellPadding: 18,
    cellRadius: 4,
    cellShadow: '0 12px 36px rgba(0,0,0,.6)',
    cellRotate: [-2, 1.5, -1, 2.2, -0.8, 1.8, -2.4, 1, -1.5],
    decoration: 'velvet-curtain',
    showGrain: true,
    grainOpacity: 0.06,
  },
  {
    id: 'v2_neon_city',
    name: 'Neon City',
    description: 'Cyberpunk neon glow on midnight blue',
    engine: 'v2',
    kind: 'body',
    palette: V2_PALETTES.neonCity,
    fonts: sansFonts,
    cellPadding: 12,
    cellRadius: 2,
    cellShadow: '0 0 30px rgba(62,230,195,.3)',
    cellRotate: [0, 0, 0, 0, 0, 0, 0, 0, 0],
    decoration: 'neon-grid',
    neonGlow: { color: NMF_BRAND_TOKENS.color.accentTeal, size: 18, intensity: 0.85 },
    showGrain: true,
    grainOpacity: 0.03,
    postProcess: 'scanlines',
  },
  {
    id: 'v2_honky_tonk',
    name: 'Honky Tonk',
    description: 'Halftone Nashville bar print, mustard and ink',
    engine: 'v2',
    kind: 'body',
    palette: V2_PALETTES.honkyTonk,
    fonts: serifFonts,
    cellPadding: 14,
    cellRadius: 0,
    cellShadow: '4px 4px 0 rgba(26,22,16,.85)',
    cellRotate: [-1.8, 1.4, -0.8, 1.6, -1.2, 1, -1.6, 1.2, -0.9],
    decoration: 'halftone-banner',
    showGrain: true,
    grainOpacity: 0.05,
    postProcess: 'halftone',
  },
  {
    id: 'v2_stadium_lights',
    name: 'Stadium Lights',
    description: 'Saturday-night arena spotlight on indigo',
    engine: 'v2',
    kind: 'body',
    palette: V2_PALETTES.stadiumLights,
    fonts: sansFonts,
    cellPadding: 10,
    cellRadius: 6,
    cellShadow: '0 16px 40px rgba(0,0,0,.5)',
    cellRotate: [0, 0, 0, 0, 0, 0, 0, 0, 0],
    decoration: 'spotlight',
    showGrain: true,
    grainOpacity: 0.04,
    postProcess: 'spotlight',
  },
  {
    id: 'v2_pearl_snap',
    name: 'Pearl Snap',
    description: 'Crisp linen with pearl studs and turquoise',
    engine: 'v2',
    kind: 'body',
    palette: V2_PALETTES.pearlSnap,
    fonts: serifFonts,
    cellPadding: 12,
    cellRadius: 2,
    cellShadow: '0 4px 14px rgba(0,0,0,.12)',
    cellRotate: [-0.8, 0.6, -0.4, 0.8, -0.5, 0.4, -0.7, 0.5, -0.3],
    decoration: 'pearl-studs',
    showGrain: true,
    grainOpacity: 0.03,
  },
];

export const V2_TITLE_TEMPLATE_PRESETS: V2TitleSlideTemplate[] = [
  {
    id: 'v2_marquee',
    name: 'Velvet Marquee',
    description: 'Theater marquee in plush rose, rotated featured cover',
    engine: 'v2',
    kind: 'title',
    palette: V2_PALETTES.velvetRoom,
    fonts: serifFonts,
    layout: 'marquee-frame',
    featuredSize: 0.5,
    featuredRadius: 4,
    featuredRotate: -3,
    showSwipePill: true,
    swipePillStyle: 'rose-tag',
    titleStyle: 'serif-italic',
    subtitleStyle: 'allcaps-spaced',
    decoration: 'marquee-bulbs',
    showGrain: true,
    grainOpacity: 0.05,
  },
  {
    id: 'v2_neon_glow',
    name: 'Neon Glow',
    description: 'Glowing title type on midnight, no rotation',
    engine: 'v2',
    kind: 'title',
    palette: V2_PALETTES.neonCity,
    fonts: sansFonts,
    layout: 'centered-stack',
    featuredSize: 0.42,
    featuredRadius: 0,
    featuredRotate: 0,
    showSwipePill: true,
    swipePillStyle: 'neon-pill',
    titleStyle: 'neon-glow',
    subtitleStyle: 'mono-spaced',
    decoration: 'neon-grid',
    postProcess: 'scanlines',
  },
  {
    id: 'v2_pearl_magazine',
    name: 'Pearl Magazine',
    description: 'Editorial cover, large serif, turquoise rule',
    engine: 'v2',
    kind: 'title',
    palette: V2_PALETTES.pearlSnap,
    fonts: serifFonts,
    layout: 'magazine-bleed',
    featuredSize: 0.55,
    featuredRadius: 0,
    featuredRotate: 0,
    showSwipePill: true,
    swipePillStyle: 'minimal-rule',
    titleStyle: 'serif-display-huge',
    subtitleStyle: 'allcaps-spaced',
    showGrain: true,
    grainOpacity: 0.03,
  },
];
