import { Link } from 'react-router-dom';

export default function Terms() {
  return (
    <div style={{ minHeight: '100vh' }}>
      <header style={{ padding: '16px 24px', borderBottom: '1px solid var(--midnight-border)', display: 'flex', alignItems: 'center', gap: 16 }}>
        <Link to="/" style={{ color: 'var(--text-muted)', fontSize: 'var(--fs-md)' }}>MMMC</Link>
        <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'var(--fs-2xl)', fontWeight: 600 }}>Terms of Service</h1>
      </header>

      <div style={{ maxWidth: 700, margin: '0 auto', padding: 32, color: 'var(--text-secondary)', lineHeight: 1.8, fontSize: 'var(--fs-lg)' }}>
        <div style={{ background: 'rgba(212,168,67,0.1)', border: '1px solid var(--gold-dark)', borderRadius: 8, padding: '12px 16px', marginBottom: 24, color: 'var(--gold)', fontSize: 'var(--fs-md)' }}>
          DRAFT — PENDING LEGAL REVIEW. These terms are not yet in effect.
        </div>

        <h2 style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)', marginBottom: 8 }}>1. Data License</h2>
        <p>By using the NMF platform, you grant MMMC Enterprises a worldwide, perpetual, irrevocable, royalty-free, sublicensable license to all data generated through platform use, including but not limited to: track selections, curation patterns, genre preferences, engagement metrics, and activity data. This license enables MMMC to aggregate, analyze, and commercialize intelligence products derived from platform activity.</p>

        <h2 style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)', marginTop: 24, marginBottom: 8 }}>2. Content Ownership</h2>
        <p>Carousel designs generated by curators belong to the curator. Platform templates, design assets, and the NMF brand belong to MMMC Enterprises. Curators may use generated carousels for any purpose including commercial posting on social media platforms.</p>

        <h2 style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)', marginTop: 24, marginBottom: 8 }}>3. Curator Profile Visibility</h2>
        <p>Registered curator profiles are visible to paying subscribers (publicists and labels). Curators may opt out of public profile visibility, which will limit access to certain platform features including the submission inbox and curator directory listing.</p>

        <h2 style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)', marginTop: 24, marginBottom: 8 }}>4. Submissions</h2>
        <p>Tracks submitted via the submission inbox are evaluated at the sole discretion of each curator. Submission does not guarantee inclusion. Publicists consent to their submission data being stored and used for matching algorithm improvement.</p>

        <h2 style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)', marginTop: 24, marginBottom: 8 }}>5. Data Retention</h2>
        <p>Platform data is retained for 5 years following account deletion. Aggregated, anonymized data derived from your activity persists indefinitely and is not subject to deletion requests.</p>

        <h2 style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)', marginTop: 24, marginBottom: 8 }}>6. Platform Modifications</h2>
        <p>MMMC reserves the right to modify platform features, pricing, and terms with 30 days written notice via email to registered users.</p>

        <p style={{ marginTop: 32, color: 'var(--text-muted)', fontSize: 'var(--fs-sm)' }}>Last updated: April 2026. Contact: legal@maxmeetsmusiccity.com</p>
      </div>
    </div>
  );
}
